# -*- coding: utf-8 -*-
"""Prac_EX1-2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CTfbU1l_pvU2gD8f-CxH8HMUTBd57VC8

# **Practicle Exercise 1**
"""

import ee
import geemap

ee.Authenticate()
ee.Initialize(project="vaibhav-gee")

map = geemap.Map()
map

Boundary = ee.FeatureCollection("projects/vaibhav-gee/assets/EX1-2/BOUNDARY")
map.addLayer(Boundary, {}, "Boundary")
Waterbodies = ee.FeatureCollection("projects/vaibhav-gee/assets/EX1-2/WATERBODIES")
map.addLayer(Waterbodies, {}, "Waterbodies")
Landuse = ee.FeatureCollection("projects/vaibhav-gee/assets/EX1-2/LANDUSE")
map.addLayer(Landuse, {}, "Landuse")
Waterways = ee.FeatureCollection("projects/vaibhav-gee/assets/EX1-2/WATERWAYS")
map.addLayer(Waterways, {}, "Waterways")
Roadways = ee.FeatureCollection("projects/vaibhav-gee/assets/EX1-2/roads")
map.addLayer(Roadways, {}, "Roadways")
Railways = ee.FeatureCollection("projects/vaibhav-gee/assets/EX1-2/RAILWAYS")
map.addLayer(Railways, {}, "Railways")
Buildings = ee.FeatureCollection("projects/vaibhav-gee/assets/EX1-2/BUILDINGS")
map.addLayer(Buildings, {}, "Buildings")
map

import geopandas as gpd

GJSON = gpd.read_file("/RAILWAYS.shp")

GJSON.to_file("RailWays.geojson",driver="GeoJSON")

GJSON = gpd.read_file("/WATERWAYS.shp")

GJSON.to_file("Waterways.geojson",driver="GeoJSON")

GJSON = gpd.read_file("/WATERBODIES.shp")

GJSON.to_file("Waterbodies.geojson",driver="GeoJSON")

GJSON = gpd.read_file("/LANDUSE.shp")

GJSON.to_file("Landuse.geojson",driver="GeoJSON")

GJSON = gpd.read_file("/BUILDINGS.shp")

GJSON.to_file("Buildings.geojson",driver="GeoJSON")

GJSON = gpd.read_file("/ROADS.shp")

GJSON.to_file("Roadways.geojson",driver="GeoJSON")

GJSON = gpd.read_file("/3Taluka's.shp")

GJSON.to_file("Boundary.geojson",driver="GeoJSON")

"""# **Practicle Exercise 2**"""

import ee
import geemap

ee.Authenticate()
ee.Initialize(project="vaibhav-gee")

"""**ROI = THANE**"""

Taluka_Bound = ee.FeatureCollection("projects/vaibhav-gee/assets/EX1-2/BOUNDARY")
map.addLayer(Taluka_Bound, {}, "3Taluka_Bound")
map.centerObject(Taluka_Bound, 10)
map

"""**DEM Dataset = ALOS DSM: Global 30m v4.1**

**Data Source = Earth Engine Data Catalog**

**Colour Palette = ['#0d0808', '#1a100f', '#2d1614', '#421a17', '#5a1e1a', '#74231d', '#8e2921', '#a83026', '#c2382b', '#db4030']**
"""

map = geemap.Map()
DEM = ee.ImageCollection("JAXA/ALOS/AW3D30/V4_1")
Taluka_DEM = DEM.filterBounds(Taluka_Bound).mosaic().clip(Taluka_Bound).select("DSM")
map.addLayer(Taluka_DEM, {"min":-1210.0,"max":108.0, "palette": ['#0d0808', '#1a100f', '#2d1614', '#421a17', '#5a1e1a', '#74231d', '#8e2921', '#a83026', '#c2382b', '#db4030']}, "DEM")
map.centerObject(Taluka_Bound, 10)
map

"""**NDVI Dataset = Landsat Collection 2 Tier 1 Level 2 8-Day NDVI Composite**

**Data Source = Earth Engine Data Catalog**

**Date = From 2025-01-01 To 2026-12-31**

**Colour Palette = ['#141712', '#252b1d', '#363f28', '#475333', '#58673e', '#697b49', '#7a8f54', '#8ba35f', '#9cb76a', '#adc178'] Colour Map = Greens**
"""

map = geemap.Map()
NDVI_2025 = ee.ImageCollection("LANDSAT/COMPOSITES/C02/T1_L2_8DAY_NDVI")
Taluka_NDVI = NDVI.filterBounds(Taluka_Bound).filterDate("2025-01-01","2025-12-31").mosaic().clip(Taluka_Bound)
Palette_2025 = {"min": -0.8, "max": -0.2, "Palette": ['#141712', '#252b1d', '#363f28', '#475333', '#58673e', '#697b49', '#7a8f54', '#8ba35f', '#9cb76a', '#adc178']}
map.addLayer(Taluka_NDVI,Palette_2025,"NDVI_2025")
map.centerObject(Taluka_Bound, 10)
map

Export_DEM = ee.batch.Export.image.toDrive(image=Taluka_DEM,
                                           description="PuneTalukas_DEM_Export",
                                           folder="GEE_Export",
                                           fileNamePrefix="DEM",
                                           region=Taluka_Bound.geometry(),
                                           scale=30,
                                           crs="EPSG:4326",
                                           maxPixels=1e13)
Export_DEM.start()

Taluka_NDVI = NDVI.mean()
Taluka_NDVI = Taluka_NDVI.clip(Taluka_Bound.geometry())
Taluka_NDVI = Taluka_NDVI.rename("NDVI")

Export_NDVI = ee.batch.Export.image.toDrive(image=Taluka_NDVI,
                                           description="PuneTalukas_NDVI_Export",
                                           folder="GEE_Export",
                                           fileNamePrefix="NDVI",
                                           region=Taluka_Bound.geometry(),
                                           scale=30,
                                           crs="EPSG:4326",
                                           maxPixels=1e13)
Export_NDVI.start()

"""**Why The Export_DEM Code and Export_NDVI Code is diffrent?**

**Because DEM is a ready to use snapshot of Elevation, so the code just grabs it and saves it.**

**But NDVI is calculated from a stack of moving images, so code just Average them out (.mean), and trim it to our boundary (.clip) and labels the result before it's ready to export.**
"""